
BUILT_IN_FUNCTIONS = {
    'println', 'print', 'readLine', 'toString', 'toLong', 'toInt', 'toDouble', 'toFloat',
    'toChar', 'toByte', 'toShort', 'toBoolean', 'length', 'substring', 'startsWith', 'endsWith',
    'contains', 'replace', 'toLowerCase', 'toUpperCase', 'trim', 'trimlStart', 'trimEnd',
    'equals', 'hashCode', 'compareTo', 'plus', 'minus', 'times', 'div', 'rem', 'rangeTo',
    'contains', 'get', 'set', 'first', 'last', 'filter', 'map', 'any', 'all', 'none', 'find',
    'groupBy', 'sortedBy', 'sortedByDescending', 'sum', 'average', 'min', 'max', 'count',
}

KEYWORD_DICT = {
    'abstract': 'abstract',
    'actual': 'actual',
    'annotation': 'annotation',
    'as': 'as',
    'break': 'break',
    'by': 'by',
    'catch': 'catch',
    'class': 'class',
    'companion': 'companion',
    'const': 'const',
    'constructor': 'constructor',
    'continue': 'continue',
    'crossinline': 'crossinline',
    'data': 'data',
    'do': 'do',
    'dynamic': 'dynamic',
    'else': 'else',
    'enum': 'enum',
    'expect': 'expect',
    'external': 'external',
    'false': 'false',
    'field': 'field',
    'final': 'final',
    'finally': 'finally',
    'for': 'for',
    'fun': 'fun',
    'get': 'get',
    'if': 'if',
    'import': 'import',
    'in': 'in',
    'infix': 'infix',
    'init': 'init',
    'inline': 'inline',
    'inner': 'inner',
    'interface': 'interface',
    'internal': 'internal',
    'is': 'is',
    'lateinit': 'lateinit',
    'noinline': 'noinline',
    'null': 'null',
    'object': 'object',
    'open': 'open',
    'operator': 'operator',
    'out': 'out',
    'override': 'override',
    'package': 'package',
    'private': 'private',
    'protected': 'protected',
    'public': 'public',
    'reified': 'reified',
    'return': 'return',
    'sealed': 'sealed',
    'set': 'set',
    'super': 'super',
    'suspend': 'suspend',
    'tailrec': 'tailrec',
    'this': 'this',
    'throw': 'throw',
    'true': 'true',
    'try': 'try',
    'typealias': 'typealias',
    'val': 'val',
    'var': 'var',
    'vararg': 'vararg',
    'when': 'when',
    'where': 'where',
    'while': 'while'
}