BUILT_IN_FUNCTIONS = {
    'print', 'input', 'len', 'str', 'int', 'float', 'bool', 'list', 'dict', 'tuple', 'set',
    'range', 'enumerate', 'zip', 'abs', 'min', 'max', 'sum', 'round', 'sorted', 'reversed',
    'any', 'all', 'isinstance', 'issubclass', 'type', 'super', 'getattr', 'setattr', 'delattr',
    'hasattr', 'callable', 'iter', 'next', 'filter', 'map', 'reduce', 'format', 'chr', 'ord',
    'hex', 'oct', 'bin', 'pow', 'divmod', 'complex', 'hash', 'id', 'repr', 'ascii', 'eval',
    'exec', 'globals', 'locals', 'compile', 'open', 'read', 'write', 'close', 'append',
    'extend', 'insert', 'remove', 'pop', 'clear', 'index', 'count', 'sort', 'reverse',
    'copy', 'deepcopy', 'update', 'get', 'items', 'keys', 'values', 'join', 'split',
    'replace', 'lower', 'upper', 'strip', 'lstrip', 'rstrip', 'startswith', 'endswith',
    'isalnum', 'isalpha', 'isdigit', 'islower', 'isupper', 'isspace', 'istitle',
}

KEYWORD_DICT = {
    'False': 'False',
    'None': 'None',
    'True': 'True',
    'and': 'and',
    'as': 'as',
    'assert': 'assert',
    'async': 'async',
    'await': 'await',
    'break': 'break',
    'class': 'class',
    'continue': 'continue',
    'def': 'def',
    'del': 'del',
    'elif': 'elif',
    'else': 'else',
    'except': 'except',
    'finally': 'finally',
    'for': 'for',
    'from': 'from',
    'global': 'global',
    'if': 'if',
    'import': 'import',
    'in': 'in',
    'is': 'is',
    'lambda': 'lambda',
    'nonlocal': 'nonlocal',
    'not': 'not',
    'or': 'or',
    'pass': 'pass',
    'raise': 'raise',
    'return': 'return',
    'try': 'try',
    'while': 'while',
    'with': 'with',
    'yield': 'yield',
    'self': 'self',
}