import os
from dotenv import load_dotenv

load_dotenv()

MODEL_NAME = os.getenv("MODEL_NAME")
KOTLIN_DATASET_PATH = os.getenv("KOTLIN_DATASET_PATH")
PYTHON_DATASET_PATH = os.getenv("PYTHON_DATASET_PATH")
MODEL_PATH = os.getenv("MODEL_PATH")
MODEL_OUTPUT_PATH = os.getenv("MODEL_OUTPUT_PATH")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
PYTHON_REPO_USERNAME = os.getenv("PYTHON_REPO_USERNAME")
PYTHON_REPO_NAME = os.getenv("PYTHON_REPO_NAME")
PYTHON_MAX_FILES = int(os.getenv("PYTHON_MAX_FILES"))
PYTHON_OUTPUT_FILE = os.getenv("PYTHON_OUTPUT_FILE")
KOTLIN_REPO_USERNAME = os.getenv("KOTLIN_REPO_USERNAME")
KOTLIN_REPO_NAME = os.getenv("KOTLIN_REPO_NAME")
KOTLIN_MAX_FILES = int(os.getenv("KOTLIN_MAX_FILES"))
KOTLIN_OUTPUT_FILE = os.getenv("KOTLIN_OUTPUT_FILE")
